# Generated by Django 5.2.5 on 2025-08-21 10:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
